### ISSUE TITLE
SKC is considered present weather instead of sky cover

### ISSUE THREAD

**Issue by hluker** [akrherz/pyIEM#453]
![image](https://user-images.githubusercontent.com/3708543/116948305-a6bba100-ac44-11eb-8890-79348d8d55fe.png)

This could be by design for all I know, but I wanted to make sure it wasn't a bug. (I guess I'm thinking in METAR logic, ala CLR).

**Comment by akrherz** [comment]
Oh, this is a TAF...  I will have to debug this some more.

**Comment by akrherz** [comment]
Well @hluker , time flies.  Indeed, this was a bug.  I've fixed it now, but need to tread carefully pushing this into prod

- [ ] ensure autoplot handles this with a now possible null sky level
- [ ] ensure the download is OK with this
- [ ] correct the archive

**Comment by akrherz** [comment]
code is now running in prod
