### ISSUE TITLE
Question on SAWProducts usage

### ISSUE THREAD

**Issue by jodylane** [akrherz/pyIEM#464]
So I have these spc watches & warnings alerts & i want to parse them & get back details like: the action, significance, phenoma, expiration, the geometry or just county / zones /parishes plus the fips associated so I can calculate the geometry myself if needed. Im looking through the codebase & found [saw.py](https://github.com/akrherz/pyIEM/blob/main/src/pyiem/nws/products/saw.py) because I think this will do everything I want 

However I am getting back an error. Wondering if this is bug, or incorrect usage, or am if there is another parser or something else I should be using
<img width="1256" alt="Screen Shot 2021-05-31 at 8 54 01 AM" src="https://user-images.githubusercontent.com/19368093/120197366-de3f4e00-c1ee-11eb-859b-f79d3369a19e.png">

Here is a sample text value Im feeding to the parser
<img width="633" alt="Screen Shot 2021-05-31 at 8 53 55 AM" src="https://user-images.githubusercontent.com/19368093/120197064-97e9ef00-c1ee-11eb-86f4-a444228057bb.png">

My code
```
# from pyiem.nws.products import parser
from pyiem.nws.products.saw import parser

text = open('./capData/spc/WOUS64_KWNS_280603_11321801').read()
print(text)
product = parser(text)
print(product)
```

**Comment by akrherz** [comment]
The `saw` module is meant to parse the `SAW` product and not the `WOU`.  For [example](https://mesonet.agron.iastate.edu/wx/afos/p.php?pil=SAW7%20%20&e=202105302259).  This particular error though typically is from a product not looking noaaport-ish (CR-CR-LF).  Could you kindy attach it to this ticket, so that I can inspect the text?  Screenshots of the text don't help too much.

**Comment by jodylane** [comment]
here is a sample file Im working with.

[WOUS64_KWNS_280353_10948093.zip](https://github.com/akrherz/pyIEM/files/6571157/WOUS64_KWNS_280353_10948093.zip)

**Comment by akrherz** [comment]
Thanks, here's an example for that product

```python
from pyiem.nws.products.vtec import parser

prod = parser(open("WOUS64_KWNS_280353_10948093").read())
print(prod.segments[0].vtec)
print(prod.segments[0].ugcs)
```

```
[<pyiem.nws.vtec.VTEC object at 0x7f683cb94d30>]
[ARC001, ARC019, ARC029, ARC039, ARC045, ARC051, ARC053, ARC059, ARC069, ARC085, ARC095, ARC097, ARC105, ARC109, ARC117, ARC119, ARC125, ARC145, ARC147]
```

**Comment by jodylane** [comment]
Thanks, @akrherz this should work just great!
